accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/update', views.update_profile, name='profile_update'),
]

campaigns/urls.py
from django.contrib import admin
from django.urls import path, include
from campaigns import views

app_name = 'campaigns'

urlpatterns = [
    path('', views.index, name='index'),

    path('campaigns', views.list_campaigns, name='campaigns_list'),
    path('campaign/<int:pk>', views.detail_campaign, name='campaign_detail'),
    path('campaign/create', views.create_campaign, name='campaign_create'),
    path('campaign/<int:pk>/settings',
         views.update_campaign, name='campaign_settings'),
    path('campaign/<int:pk>/delete', views.delete_campaign, name='campaign_delete'),


    path('campaign/<int:pk>/recipient/create',
         views.create_recipient, name='recipient_create'),
    path('campaign/<int:pk>/recipient/upload',
         views.upload_recipient, name='recipient_upload'),
    path('campaign/<int:pk>/recipient/<int:rpk>/update',
         views.update_recipient, name='recipient_update'),
    path('campaign/<int:pk>/signup',
         views.signup_recipient, name='recipient_signup'),
    path('recipient/<int:pk>/unsubscribe/<str:unsub_id>',
         views.unsubscribe_recipient, name='ubsubscribe'),


    path('settings/email-templates', views.list_email_templates,
         name='email_templates_list'),
    path('settings/email-template/create',
         views.create_email_template, name='email_template_create'),
    path('settings/email-template/<int:pk>/update',
         views.update_email_template, name='email_template_update'),
    path('settings/email-template/<int:pk>/duplicate',
         views.duplicate_email_template, name='email_template_duplicate'),
    path('settings/email-template/<int:pk>/delete',
         views.delete_email_template, name='email_template_delete'),


    path('settings/review-pages', views.list_review_page_templates,
         name='review_page_templates_list'),
    path('settings/review-page/<int:pk>/update',
         views.update_review_page_template, name='review_page_template_update'),
    path('settings/review-page/create', views.create_review_page_template,
         name='review_page_template_create'),
    path('settings/review-template/<int:pk>/duplicate',
         views.duplicate_review_page_template, name='review_page_template_duplicate'),
    path('settings/review-page/<int:pk>/delete',
         views.delete_review_page_template, name='review_page_template_delete'),


    path('settings/routing', views.list_routes, name='routes_list'),
    path('settings/routing/create', views.create_route, name='route_create'),
    path('settings/routing/<int:pk>/update',
         views.update_route, name='route_update'),
    path('settings/routing/<int:pk>/delete',
         views.delete_route, name='route_delete'),


    path('settings/conditions', views.list_conditions, name='conditions_list'),
    path('settings/condition/create',
         views.create_condition, name='condition_create'),
    path('settings/condition/<int:pk>/delete',
         views.delete_condition, name='condition_delete'),
    path('settings/condition/<int:pk>/update',
         views.update_condition, name='condition_update'),


    path('settings/criteria', views.list_review_criteria,
         name='review_criteria_list'),
    path('settings/criteria/create', views.create_review_criteria,
         name='review_criteria_create'),
    path('settings/criteria/<int:pk>/update',
         views.update_review_criteria, name='review_criteria_update'),
    path('settings/criteria/<int:pk>/delete',
         views.delete_review_criteria, name='review_criteria_delete'),


    path('evaluation/<int:epk>/redirect/route/<int:rpk>',
         views.post_redirect, name='redirect'),
    path('evaluation/<str:slug>', views.submit_evaluation,
         name='evaluation_submit'),
    path('evaluation/<str:slug>/comments',
         views.submit_comments, name='comments_submit'),
    path('evaluation/<str:slug>/received', views.thank_you, name='thank_you'),


    path('evaluation/email/<str:slug>',
         views.email_evaluation, name='evaluation_email'),
    path('evaluation/email/<str:slug>/<int:rating>',
         views.email_router, name='email_router'),
    path('evaluation/email/<str:slug>/redirect/route/<int:rpk>',
         views.email_recapture, name='recapture_email'),

]

reviewproject/urls.py
from django.contrib import admin
from django.urls import path, include

import allauth ### REQUIRED FOR ALLAUTH
from django.conf import settings ### REQUIRED FOR STATIC UPLOADS
from django.conf.urls.static import static ### REQUIRED FOR STATIC UPLOADS
from django.conf.urls import handler400, handler500 ### REQUIRED FOR ERROR HANDLING

urlpatterns = [
    path('', include("campaigns.urls", namespace="campaigns")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include('allauth.urls')), ### REQUIRED FOR ALLAUTH: AUTOMATIC ACCESS TO ALL VIEWS
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) ### REQUIRED TO VIEW UPLOADED STATIC FILES

handler404 = 'campaigns.views.handler404'
handler500 = 'campaigns.views.handler500'

campaigns/models.py
from django.db import models
from accounts.models import CustomUser
from campaigns.choices import *
from reviewproject.defaults import *
from django.dispatch import receiver
from django.db.models import Q
from django.db.models.signals import post_save, post_delete, pre_save
import uuid
from django.db import transaction
import secrets
from campaigns.utils import hex_to_rgb, darken_color


import re
import publicsuffix
import urllib.parse


class EmailTemplate(models.Model):
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='email_templates_from_creator')
    template_name = models.CharField(
        max_length=48, default=EMAIL_NAME_DEFAULT)
    subject_line = models.CharField(
        max_length=48, default=EMAIL_SUBJECT_DEFAULT)
    heading = models.CharField(max_length=48, default=EMAIL_HEADING_DEFAULT)
    body = models.TextField(max_length=750, default=EMAIL_BODY_DEFAULT)
    sub_heading = models.CharField(
        max_length=48, default=EMAIL_SUB_HEADING_DEFAULT)
    sub_body = models.TextField(max_length=750, default=EMAIL_SUB_BODY_DEFAULT)
    button = models.CharField(max_length=24, default=EMAIL_BUTTON_DEFAULT)
    heading_color = models.CharField(
        max_length=7, default=HEADING_COLOR_DEFAULT)
    body_color = models.CharField(max_length=7, default=BODY_COLOR_DEFAULT)
    background_color = models.CharField(
        max_length=7, default=BACKGROUND_COLOR_DEFAULT)
    button_color = models.CharField(max_length=7, default=BUTTON_COLOR_DEFAULT)
    html_template = models.SmallIntegerField(
        choices=HTML_EMAIL_OPTIONS, default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return str('{} ({})').format(self.template_name, self.creator)


class IntroTemplate(models.Model):
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='intro_templates_from_creator')
    subject_line = models.CharField(
        max_length=24, default=EVALUATION_HEADING_DEFAULT)
    body = models.TextField(
        max_length=750, default=EVALUATION_SUBHEADING_DEFAULT)
    comments_label = models.CharField(
        max_length=48, default=COMMENTS_HEADING_DEFAULT)
    comments_placeholder = models.TextField(
        max_length=250, default=COMMENTS_PLACEHOLDER_DEFAULT)
    redirect_heading = models.CharField(
        max_length=48, default=REDIRECT_HEADING_DEFAULT)
    redirect_subheading = models.TextField(
        max_length=200, default=REDIRECT_SUBHEADING_DEFAULT)
    thankyou_heading = models.CharField(
        max_length=48, default=THANKYOU_HEADING_DEFAULT)
    thankyou_subheading = models.TextField(
        max_length=150, default=THANKYOU_SUBHEADING_DEFAULT)
    navbar_color = models.CharField(max_length=7, default=NAVBAR_COLOR_DEFAULT)
    heading_color = models.CharField(
        max_length=7, default=HEADING_COLOR_DEFAULT)
    subheading_color = models.CharField(
        max_length=7, default=SUBHEADING_COLOR_DEFAULT)
    body_color = models.CharField(max_length=7, default=BODY_COLOR_DEFAULT)
    background_color = models.CharField(
        max_length=7, default=BACKGROUND_COLOR_DEFAULT)
    button_color = models.CharField(max_length=7, default=BUTTON_COLOR_DEFAULT)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return str('{} ({})').format(self.subject_line, self.creator)

    def hover_button_color(self):
        r, g, b = hex_to_rgb(self.button_color)
        return darken_color(r, g, b, 0.15)


class CriteriaTemplate(models.Model):
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='criteria_templates_from_creator')
    name = models.CharField(max_length=30, default="Quality")
    label = models.CharField(max_length=120, default=CRITERIA_LABEL_TEMPLATE)
    ladder = models.SmallIntegerField(choices=SCALE_OPTIONS, default=5)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return str('{} ({})').format(self.label, self.creator)


class Recipient(models.Model):
    subscribed = models.BooleanField(default=True)
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='recipients_from_creator')
    first_name = models.CharField(max_length=48)
    last_name = models.CharField(max_length=48)
    email = models.EmailField()
    extra_field_1 = models.CharField(max_length=48, null=True, blank=True)
    extra_field_2 = models.CharField(max_length=48, null=True, blank=True)
    unsub_id = models.CharField(max_length=48, unique=True)

    """
    auto_create_unsub_hash_with_recipient() signal must be one single transaction
    """
    @transaction.atomic()
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def __str__(self):
        return str('{} {}').format(self.first_name, self.last_name)


class Condition(models.Model):
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='conditions_from_creator')
    input_field = models.SmallIntegerField(choices=INPUT_FIELDS)
    comparison_operator = models.SmallIntegerField(
        choices=COMPARISON_OPERATORS, default=0)
    passing_value = models.CharField(max_length=48)

    def __str__(self):
        return str('{} {} {}').format(self.get_input_field_display(), self.get_comparison_operator_display(), self.passing_value)


class Route(models.Model):
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='routes_from_creator')
    name = models.CharField(max_length=48)
    conditions = models.ManyToManyField(
        Condition, related_name='routes_from_condition', blank=True)
    priority = models.SmallIntegerField(choices=PRIORITY_LEVEL, default=0)
    url = models.URLField()
    url_thumbnail = models.URLField(max_length=2000)
    thumbnail = models.FileField(upload_to='media/routes')

    def clean_website_url(self):
        # import pdb; pdb.set_trace()
        url_clean = ''
        if self.website:
            url = re.compile(r"https?://(www\.)?")
            url_clean = "www." + url.sub('', self.website).strip().strip('/')
        return url_clean

    def __str__(self):
        return self.name


class Campaign(models.Model):
    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='campaigns_from_creator')
    title = models.CharField(max_length=48, default='New campaign')
    extra_field1_label = models.CharField(max_length=48, null=True, blank=True)
    extra_field2_label = models.CharField(max_length=48, null=True, blank=True)
    criteria_templates = models.ManyToManyField(
        CriteriaTemplate, related_name='campaigns_from_criteria')
    intro_template = models.ForeignKey(
        IntroTemplate, on_delete=models.CASCADE, related_name='campaigns_from_intro_template')
    route = models.ManyToManyField(
        Route, related_name='campaigns_from_route', blank=True)
    fail_url = models.URLField(null=True, blank=True)
    fail_timeout = models.SmallIntegerField(
        choices=TIMEOUT_OPTIONS, null=True, blank=True)

    @property
    def completion_rate(self):
        # import pdb
        # pdb.set_trace()
        review_requests = self.review_requests_from_campaign.all().count()
        has_comments = self.review_requests_from_campaign.all().filter(
            ~Q(evaluations_from_review_request__comments=None)).count()
        routed_externally = self.review_requests_from_campaign.all().filter(
            ~Q(Q(evaluations_from_review_request__routedTo="Internal") | Q(evaluations_from_review_request__routedTo=None))).count()
        clicks = has_comments + routed_externally
        return round(clicks/review_requests * 100)

    @property
    def success_count(self):
        return self.review_requests_from_campaign.all().filter(evaluations_from_review_request__result=0).count()

    @property
    def failure_count(self):
        return self.review_requests_from_campaign.all().filter(evaluations_from_review_request__result=1).count()

    @property
    def click_rate(self):

        evaluations = Evaluation.objects.filter(
            review_request__campaign__id=self.id).count()

        requests = self.review_requests_from_campaign.all().count()

        return round(evaluations/requests * 100)

    def __str__(self):
        return str('Campaign {}').format(self.id)


class ReviewRequest(models.Model):
    campaign = models.ForeignKey(
        Campaign, on_delete=models.CASCADE, related_name='review_requests_from_campaign')
    recipient = models.ForeignKey(
        Recipient, on_delete=models.CASCADE, related_name='review_requests_from_recipient')
    slug = models.CharField(max_length=250, unique=True)

    def most_recent_message(self):
        messages = self.messages_from_review_request.all().order_by('-sent')
        if messages:
            message = messages[0]
            return message
        return None

    def number_of_messages(self):
        messages = self.messages_from_review_request.all()
        return messages.count()

    def status(self):

        clicked = self.evaluations_from_review_request.all().count() > 0
        has_comments = False
        routed_externally = False
        if clicked:
            has_comments = self.evaluations_from_review_request.all().order_by(
                '-id')[0].comments != None
            routed_externally = not (self.evaluations_from_review_request.all().order_by(
                '-id')[0].routedTo == 'Internal' or self.evaluations_from_review_request.all().order_by('-id')[0].routedTo == None)

        sent = self.messages_from_review_request.all()
        subscribed = self.recipient.subscribed

        # import pdb
        # pdb.set_trace()
        if not subscribed:
            return 'Unsubbed'
        elif has_comments or routed_externally:
            return 'Completed'
        elif clicked:
            return 'Clicked'
        elif sent:
            return 'Sent'

campaigns/templates/campaigns/breadcrumbs.html
<div class="breadcrumb">
    <!-- Campaigns -->
    {% if view_name == 'campaigns_list' %}
        <span><a href="/">Home</a> › <strong>Campaigns</strong></span>
    {% elif view_name == 'campaign_detail' %}
        <span><a href="/">Home</a> › <a href="{% url 'campaigns:campaigns_list' %}">Campaigns</a> ›  <strong>Details</strong></span>

    <!-- Page Templates -->
    {% elif view_name == 'review_page_templates_list' %}
        <span><a href="/">Home</a> › <strong>Page Templates</strong></span>
    {% elif view_name == 'review_page_template_update' %}
        <span><a href="/">Home</a> › <a href="{% url 'campaigns:review_page_templates_list' %}">Page Templates</a> ›  <strong>Update Page</strong></span>

    <!-- Email Templates -->
    {% elif view_name == 'email_templates_list' %}
        <span><a href="/">Home</a> › <strong>Email Templates</strong></span>
    {% elif view_name == 'email_template_update' %}
        <span><a href="/">Home</a> › <a href="{% url 'campaigns:email_templates_list' %}">Email Templates</a> ›  <strong>Update Email</strong></span>

    <!-- Routing -->
    {% elif view_name == 'routes_list' or view_name == 'review_criteria_list' or view_name == 'conditions_list' %}
        <span><a href="/">Home</a> › <strong>Routing</strong></span>
    {% elif view_name == 'condition_update' or view_name == 'condition_create' %}
        <span><a href="/">Home</a> › <a href="{% url 'campaigns:routes_list' %}">Routing</a> › <a href="{% url 'campaigns:conditions_list' %}">Conditions</a> ›  <strong>Condition Details</strong></span>
    {% elif view_name == 'review_criteria_update' or view_name == 'review_criteria_create' %}
        <span><a href="/">Home</a> › <a href="{% url 'campaigns:routes_list' %}">Routing</a> › <a href="{% url 'campaigns:review_criteria_list' %}">Criteria</a> ›  <strong>Criterion Details</strong></span>
    {% elif view_name == 'route_update' or view_name == 'route_create' %}
        <span><a href="/">Home</a> › <a href="{% url 'campaigns:routes_list' %}">Routing</a> › <a href="{% url 'campaigns:routes_list' %}">Routes</a> ›  <strong>Route Details</strong></span>

    <!-- Account -->
    {% elif view_name == 'profile_update' %}
        <span><a href="/">Home</a> › <strong>Update Profile</strong></span>

    {% endif %}
</div>




<style>
    .breadcrumb{
        margin: 20px 0px;
    }
</style>

campaigns/templates/campaigns/campaign.html
<head>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
</head>

<h1>{{campaign.title}}</h1>

{% include "campaigns/breadcrumbs.html"%}

<ul>
    <li><a href="{% url 'campaigns:recipient_create' pk=campaign.id %}">+ Add a recipient</a></li>
    <li><a href="{% url 'campaigns:recipient_upload' pk=campaign.id %}">+ Upload recipient list</a></li>
    <li><a href="{% url 'campaigns:campaign_settings' pk=campaign.id %}">Campaign settings</a></li>
    <li><button onClick="CopyClipBoard('{{url_signup_recipient}}')">Copy campaign link</button></li>
    
</ul>




{% if review_requests.exists %}

<h3 style="margin:30px 0px 0px 0px">
    Statistics
</h3>

<div class="flex-row">
    <div class="card">
        <h1 class="card-stat">{{campaign.failure_count}}</h1>
        <div class="card-label">Negative<br> Prevented</div>
    </div>
    <div class="card">
        <h1 class="card-stat">{{campaign.success_count}}</h1>
        <div class="card-label">Hot<br> Leads</div>
    </div>
    <div class="card">
        <h1 class="card-stat">{{campaign.click_rate}}<span style="font-size: 0.5em;">%</span></h1>
        <div class="card-label">Click<br> Rate</div>
    </div>
    <div class="card">
        <h1 class="card-stat">{{campaign.completion_rate}}<span style="font-size: 0.5em;">%</span></h1>
        <div class="card-label">Completion<br> Rate</div>
    </div>
</div>

<form method="post" action="">
        {% csrf_token %}
        <input type="submit" name="delete" value="Delete">
        <input type="submit" name="send" value="Send">

        {{form}}

        <button type="submit" name="edit" value="Edit">
            <i style="font-size: 17px; color: rgb(27, 27, 27);"class="fas fa-edit"></i>
        </button>
        
        <a  style="text-decoration: none;" href="{% url 'campaigns:email_template_create' %}?next={{ request.path|urlencode }}">
            <i style="font-size: 18px; color: rgb(27, 27, 27); "class="fas fa-plus-square"></i>
        </a>

        <button type="submit" name="test" value="Test">
            <i style="font-size: 17px; color: rgb(27, 27, 27);"class="fas fa-vial"></i>
        </button>

        

      
{% endif %} 
    <table>
        <tr>
            <th>{% if review_requests.exists %}<input type="checkbox" onClick="toggle(this)"/>{% endif %} </th>
            <th>#</th>
            <th>Status</th>
            <th>Result</th>
            <th>Last sent</th>
            <th>Total sent</th>
            <th>Recipient</th>
            <th>Email</th>
            {% if campaign.extra_field1_label %}
                <th> {{campaign.extra_field1_label}}</th>
            {% endif %}
            {% if campaign.extra_field2_label %}
                <th> {{campaign.extra_field2_label}}</th>
            {% endif %}
            <th>Email Template</th>
            <th>Routed To</th>
            <th>Action</th>
        </tr>
        {% if review_requests.exists %}
            {% for request in review_requests %}
            <tr {% if not request.recipient.subscribed %} class='unsubscribed' {% endif %}>
                <td><input type="checkbox" id={{request.id}} name="selected_{{request.id}}" {% if not request.recipient.subscribed %} disabled {% endif %}></td>
                <td>{{forloop.counter}}</td>
                <td>{{request.status}}</td>
                <td>
                    <div class="tooltip">{{request.evaluations_from_review_request.all.last.get_result_display}}
                        <div class="tooltiptext">
                            {% if request.evaluations_from_review_request.all.last.scores_from_evaluation.all %}
                                {% for score in request.evaluations_from_review_request.all.last.scores_from_evaluation.all %}
                                    {{score.criteria.name}}: {{score.value}}/{{score.criteria.get_ladder_display}}
                                    
                                {% endfor %}
                            {% else %}
                                <span>Evaluation skipped.</span>
                            {% endif %}
                             
                            {% if request.evaluations_from_review_request.all.last.comments %}
                               <p>"{{request.evaluations_from_review_request.all.last.comments}}"</p>
                               <p>{{request.evaluations_from_review_request.all.last.created}}</p> 
                            {% endif %}
                        </div>
                    </div>
                </td>
                <td>{% if request.most_recent_message %} {{request.most_recent_message.sent}} {% endif %}</td>
                <td>{% if request.most_recent_message %} {{request.number_of_messages}} {% endif %}</td>
                <td>{{request.recipient}}</td>
                <td>{{request.recipient.email}}</td>
                {% if campaign.extra_field1_label %}
                    <td>{{request.recipient.extra_field_1}}</td>
                {% endif %}
                {% if campaign.extra_field2_label %}
                    <td>{{request.recipient.extra_field_2}}</td>
                {% endif %}
                <td>{% if request.most_recent_message %} {{request.most_recent_message.email_template.template_name}} {% endif %}</td>


                <td>
                    {% if request.evaluations_from_review_request.all.last.routedTo != None %}
                        {{request.evaluations_from_review_request.all.last.routedTo}}
                    {% endif %}
                </td>
                <td><a href="{% url 'campaigns:recipient_update' pk=campaign.id rpk=request.recipient.id %}">Edit</a> |
                    <a href="{% url 'campaigns:evaluation_submit' slug=request.slug %}" target="_blank">Evaluation</a> |
                    <a href="{% url 'campaigns:evaluation_email' slug=request.slug %}" target="_blank">Email Evaluation</a>

                </td>
            </tr>
            {% endfor %}
        {% endif %}
    </table>

</form>
</html>


<style>
    table, th, td {
        border-bottom: 1px solid #c3c3c3;
        border-collapse: collapse;
        width:auto;
    }

    .unsubscribed {
        color: lightgray
    }

    button {
        background: none!important;
        border: none;
        padding: 0!important;
        /*optional*/
        font-family: 'Times New Roman', serif;
        font-size: 16px;
        color: #551A8B;
        text-decoration: underline;
        cursor: pointer;
    }

    .flex-row{
        display: flex;
        flex-direction: row;
    }

    .card{
        display: flex;
        flex-direction: column;
        min-width: 75px;
        justify-content: center;
        margin: 10px 10px 20px 0px;
        padding: 7px 0px;
        text-align: center;
        border: solid 1px lightgray;
        border-radius: 8px;
    }

    .card-stat{
        margin: 0px 20px
    }
    .card-label{
        color: grey;
        text-transform: uppercase;
        font-size: 0.6em;
    }


    .tooltip {
    position: relative;
    display: inline-block;
    border-bottom: 1px dotted black;
    }

    .tooltip .tooltiptext {
    font-size: 0.9em;
    visibility: hidden;
    width: 200px;
    background-color: rgb(34, 34, 34);
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 15px;


    /* Position the tooltip */
    position: absolute;
    z-index: 1;
    }

    .tooltip:hover .tooltiptext {
    visibility: visible;
   
    }


</style>

<script>
    function CopyClipBoard(str) {
        const element = document.createElement('textarea');
        element.value = str;
        document.body.appendChild(element);
        document.body.appendChild(element);
        element.select();
        document.execCommand('copy');
        document.body.removeChild(element);
    }

    function toggle(source) {
        checkboxes = document.querySelectorAll("[name^=selected_]")
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }



</script>

campaigns/templates/campaigns/campaign_setup_form.html
<h1>Campaign {{pk}}</h1>
<h2>Settings</h2>


<form  method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
<a href="{% url 'campaigns:campaign_detail' pk=pk %}"><button>Cancel</button></a>

campaigns/templates/campaigns/conditions_list.html
<h1>Routing</h1>

{% include "campaigns/breadcrumbs.html"%}

<ul>
    <li ><a href="{% url 'campaigns:routes_list' %}">Routes</a></li>
    <li ><a href="{% url 'campaigns:review_criteria_list' %}">Criteria</a></li>
    <li ><a href="{% url 'campaigns:conditions_list' %}" class="active">Conditions</a></li>
</ul>

<a href="{% url 'campaigns:condition_create' %}">+ Create a condition</a>
<table>
    <tr>
        <th>#</th>
        <th>Condition</th>
        <th>Action</th>
    </tr>
    {% for condition in condition_list %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{condition}}</td>
        <td><a href="{% url 'campaigns:condition_update' pk=condition.id %}">Edit</a> |
            <a href="{% url 'campaigns:condition_delete' pk=condition.id %}">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>


<style>
    table, th, td {
        border-bottom: 1px solid #c3c3c3;
        border-collapse: collapse;
        width:auto;
        /* padding: 5px 50px 5px 5px; */
    }

    .active {
        font-weight: 600;
    }

    .inactive {
        color: lightgray
    }
</style>

campaigns/templates/campaigns/criteria_list.html
<h1>Routing</h1>

{% include "campaigns/breadcrumbs.html"%}

<ul>
    <li ><a href="{% url 'campaigns:routes_list' %}">Routes</a></li>
    <li ><a href="{% url 'campaigns:review_criteria_list' %}" class="active">Criteria</a></li>
    <li ><a href="{% url 'campaigns:conditions_list' %}">Conditions</a></li>
</ul>


<a href="{% url 'campaigns:review_criteria_create' %}">+ Create a criteria</a>


    <table>
        <tr>
            <th>#</th>
            <th>Label</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
        {% for criteria in review_criteria_list %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{criteria.name}}</td>
            <td>{{criteria.label}}</td>
            <td><a href="{% url 'campaigns:review_criteria_update' pk=criteria.id %}">Edit</a> |
                {% if forloop.counter == 1 %}
                    <a class='inactive'>Delete</a>
                {% else %}
                    <a href="{% url 'campaigns:review_criteria_delete' pk=criteria.id %}">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>


</form>





<style>
    table, th, td {
        border-bottom: 1px solid #c3c3c3;
        border-collapse: collapse;
        width:auto;
        /* padding: 5px 50px 5px 5px; */
    }

    .active {
        font-weight: 600;
    }

    .inactive {
        color: lightgray
    }
</style>

campaigns/templates/campaigns/ubsubscribed.html
<h1>You have been unsubscribed.</h1>