accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/update', views.update_profile, name='profile_update'),
]

campaigns/urls.py
from django.contrib import admin
from django.urls import path, include
from campaigns import views

app_name = 'campaigns'

urlpatterns = [
    path('', views.index, name='index'),

    path('campaigns', views.list_campaigns, name='campaigns_list'),
    path('campaign/<int:pk>', views.detail_campaign, name='campaign_detail'),
    path('campaign/create', views.create_campaign, name='campaign_create'),
    path('campaign/<int:pk>/settings',
         views.update_campaign, name='campaign_settings'),
    path('campaign/<int:pk>/delete', views.delete_campaign, name='campaign_delete'),


    path('campaign/<int:pk>/recipient/create',
         views.create_recipient, name='recipient_create'),
    path('campaign/<int:pk>/recipient/upload',
         views.upload_recipient, name='recipient_upload'),
    path('campaign/<int:pk>/recipient/<int:rpk>/update',
         views.update_recipient, name='recipient_update'),
    path('campaign/<int:pk>/signup',
         views.signup_recipient, name='recipient_signup'),
    path('recipient/<int:pk>/unsubscribe/<str:unsub_id>',
         views.unsubscribe_recipient, name='ubsubscribe'),


    path('settings/email-templates', views.list_email_templates,
         name='email_templates_list'),
    path('settings/email-template/create',
         views.create_email_template, name='email_template_create'),
    path('settings/email-template/<int:pk>/update',
         views.update_email_template, name='email_template_update'),
    path('settings/email-template/<int:pk>/duplicate',
         views.duplicate_email_template, name='email_template_duplicate'),
    path('settings/email-template/<int:pk>/delete',
         views.delete_email_template, name='email_template_delete'),


    path('settings/review-pages', views.list_review_page_templates,
         name='review_page_templates_list'),
    path('settings/review-page/<int:pk>/update',
         views.update_review_page_template, name='review_page_template_update'),
    path('settings/review-page/create', views.create_review_page_template,
         name='review_page_template_create'),
    path('settings/review-template/<int:pk>/duplicate',
         views.duplicate_review_page_template, name='review_page_template_duplicate'),
    path('settings/review-page/<int:pk>/delete',
         views.delete_review_page_template, name='review_page_template_delete'),


    path('settings/routing', views.list_routes, name='routes_list'),
    path('settings/routing/create', views.create_route, name='route_create'),
    path('settings/routing/<int:pk>/update',
         views.update_route, name='route_update'),
    path('settings/routing/<int:pk>/delete',
         views.delete_route, name='route_delete'),


    path('settings/conditions', views.list_conditions, name='conditions_list'),
    path('settings/condition/create',
         views.create_condition, name='condition_create'),
    path('settings/condition/<int:pk>/delete',
         views.delete_condition, name='condition_delete'),
    path('settings/condition/<int:pk>/update',
         views.update_condition, name='condition_update'),


    path('settings/criteria', views.list_review_criteria,
         name='review_criteria_list'),
    path('settings/criteria/create', views.create_review_criteria,
         name='review_criteria_create'),
    path('settings/criteria/<int:pk>/update',
         views.update_review_criteria, name='review_criteria_update'),
    path('settings/criteria/<int:pk>/delete',
         views.delete_review_criteria, name='review_criteria_delete'),


    path('evaluation/<int:epk>/redirect/route/<int:rpk>',
         views.post_redirect, name='redirect'),
    path('evaluation/<str:slug>', views.submit_evaluation,
         name='evaluation_submit'),
    path('evaluation/<str:slug>/comments',
         views.submit_comments, name='comments_submit'),
    path('evaluation/<str:slug>/received', views.thank_you, name='thank_you'),


    path('evaluation/email/<str:slug>',
         views.email_evaluation, name='evaluation_email'),
    path('evaluation/email/<str:slug>/<int:rating>',
         views.email_router, name='email_router'),
    path('evaluation/email/<str:slug>/redirect/route/<int:rpk>',
         views.email_recapture, name='recapture_email'),

]

reviewproject/urls.py
from django.contrib import admin
from django.urls import path, include

import allauth ### REQUIRED FOR ALLAUTH
from django.conf import settings ### REQUIRED FOR STATIC UPLOADS
from django.conf.urls.static import static ### REQUIRED FOR STATIC UPLOADS
from django.conf.urls import handler400, handler500 ### REQUIRED FOR ERROR HANDLING

urlpatterns = [
    path('', include("campaigns.urls", namespace="campaigns")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include('allauth.urls')), ### REQUIRED FOR ALLAUTH: AUTOMATIC ACCESS TO ALL VIEWS
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) ### REQUIRED TO VIEW UPLOADED STATIC FILES

handler404 = 'campaigns.views.handler404'
handler500 = 'campaigns.views.handler500'

campaigns/views.py
# from reviewproject.campaigns.models import Evaluation
from django.urls import resolve
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from campaigns.models import *
from campaigns.forms import *
from django.db import transaction
import csv
import io
from django.shortcuts import render
from django.contrib import messages
import datetime
from campaigns.utils import send_mass_html_mail, to_snake_case, test_scores, is_email_valid, find_duplicates, hex_to_rgb, create_context_email, url_to_view
from django.template.loader import render_to_string
from html2text import html2text
from django.template import Template, Context
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.decorators import login_required
from reviewproject.decorators import is_creator_required
from django.shortcuts import get_object_or_404
import pandas
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.template import RequestContext

from campaigns.choices import *

# Create your views here.


@login_required
def index(request):
    user = request.user
    context = {
        'user': user
    }

    return render(request, "campaigns/index.html", context)


"""
Campaigns
"""


@login_required
def list_campaigns(request):

    user = request.user

    context = {
        'campaigns': Campaign.objects.filter(creator=user),
        'view_name': url_to_view(request.path)
    }
    return render(request, "campaigns/campaigns.html", context)


@login_required
@is_creator_required
@transaction.atomic()
def detail_campaign(request, pk):

    user = request.user
    campaign = Campaign.objects.get(id=pk)
    review_requests = campaign.review_requests_from_campaign.all()

    if request.method == "POST":
        selected_ids = [box[9:]
                        for box in request.POST.keys() if box.startswith("selected_")]
        selected_requests = ReviewRequest.objects.filter(
            id__in=selected_ids)  # Turn ID list [23, 25] into QuerySet

        email_list = []
        message_list = []
        form = CampaignForm(request.POST, user=user)
        form.fields['email_template'].required = True
        sender = request.user

        if 'delete' in request.POST:
            selected_requests.delete()

        if 'edit' in request.POST:

            if form.is_valid():
                data = form.cleaned_data
                email_template = data['email_template']
                url_redirect = reverse('campaigns:email_template_update', kwargs={
                    'pk': email_template.id}) + '?next=/campaign/{}'.format(pk)

                return redirect(url_redirect)

            return render(request, 'campaigns/campaign.html', {'form': form, 'pk': pk, 'campaign': campaign, 'review_requests': review_requests})

        if 'test' in request.POST:

            if form.is_valid():
                data = form.cleaned_data
                email_template = data['email_template']
                html_template_url = 'campaigns/emails/{}.html'.format(
                    HTML_EMAIL_OPTIONS[email_template.html_template][1].replace(" ", "_").lower())
                recipient = request.user

                context_email = create_context_email(
                    request, email_template, recipient, sender, campaign)
                html_message = render_to_string(
                    html_template_url, context_email)
                plain_message = html2text(html_message)

                email_list.append((context_email['subject_line'], plain_message,
                                  html_message, context_email['sender_email'], [recipient.test_email]))

                # import pdb
                # pdb.set_trace()
                send_mass_html_mail(email_list)

            return render(request, 'campaigns/campaign.html', {'form': form, 'pk': pk, 'campaign': campaign, 'review_requests': review_requests})

        if 'send' in request.POST:

            if form.is_valid():
                data = form.cleaned_data
                email_template = data['email_template']
                html_template_url = 'campaigns/emails/{}.html'.format(
                    HTML_EMAIL_OPTIONS[email_template.html_template][1].replace(" ", "_").lower())

                for review_request in selected_requests:
                    recipient = review_request.recipient
                    context_email = create_context_email(
                        request, email_template, recipient, sender, campaign, review_request)

                    html_message = render_to_string(
                        html_template_url, context_email)
                    plain_message = html2text(html_message)

                    email_list.append((context_email['subject_line'], plain_message,
                                       html_message, context_email['sender_email'], [recipient.email]))

                    tuple(message_list)
                    message_list.append(Message(
                        email_template=email_template, review_request=review_request, sent=datetime.datetime.now()))

                # import pdb
                # pdb.set_trace()
                Message.objects.bulk_create(message_list)
                send_mass_html_mail(email_list, bcc=[request.user.email])

            # return redirect('campaigns:campaign_detail', pk=pk)
            return render(request, 'campaigns/campaign.html', {'form': form, 'pk': pk, 'campaign': campaign, 'review_requests': review_requests})

    context = {
        'campaign': campaign,
        'url_signup_recipient': request.build_absolute_uri(reverse('campaigns:recipient_signup', kwargs={'pk': campaign.pk})),
        'review_requests': review_requests,
        'form': CampaignForm(user=user),
        'view_name': url_to_view(request.path)
    }
    return render(request, "campaigns/campaign.html", context)


@login_required
def create_campaign(request):

    # import pdb; pdb.set_trace()
    instance = Campaign.objects.create(
        creator=request.user,
        intro_template=IntroTemplate.objects.filter(creator=request.user).get(
            is_default=True)  # Default intro template
    )

    defaultCriteria = CriteriaTemplate.objects.filter(
        creator=request.user).get(is_default=True)  # Default criteria
    instance.criteria_templates.add(defaultCriteria)

    return redirect('campaigns:campaigns_list')


@login_required
@is_creator_required
def update_campaign(request, pk):

    print(url_to_view(request.path))
    user = request.user
    campaign = Campaign.objects.get(id=pk)

    # import pdb; pdb.set_trace()
    if request.method == "POST":
        form = CampaignSettingsForm(request.POST, user=user)
        if form.is_valid():
            data = form.cleaned_data
            campaign.title = data['title']
            campaign.extra_field1_label = data['extra_field1_label']
            campaign.extra_field2_label = data['extra_field2_label']
            campaign.intro_template = data['intro_template']
            campaign.criteria_templates.set(data['criteria_templates'])
            campaign.route.set(data['route'])

            campaign.fail_url = data['fail_url']
            campaign.fail_timeout = data['fail_timeout']

            campaign.save()

            return redirect('campaigns:campaign_detail', pk=pk)

    form = CampaignSettingsForm(instance=campaign, user=user)

    context = {
        'pk': pk,
        'form': form,
    }

    return render(request, 'campaigns/campaign_setup_form.html', context)


@login_required
@is_creator_required
def delete_campaign(request, pk):
    campaign = Campaign.objects.get(id=pk)
    campaign.delete()
    return redirect('campaigns:campaigns_list')


"""
Recipients & Requests
"""


@login_required
@is_creator_required
@transaction.atomic()
def create_recipient(request, pk):

    print(url_to_view(request.path))

    campaign = Campaign.objects.get(id=pk)

    if request.method == "POST":
        form = RecipientForm(request.POST, campaign=campaign)
        if form.is_valid():
            data = form.cleaned_data
            # import pdb; pdb.set_trace()
            newRecipient = Recipient.objects.create(
                creator=campaign.creator,
                first_name=data['first_name'],
                last_name=data['last_name'],
                email=data['email']
            )

            if 'extra_field_1' in data:
                newRecipient.extra_field_1 = data['extra_field_1']
            if 'extra_field_2' in data:
                newRecipient.extra_field_2 = data['extra_field_2']
            newRecipient.save()

            ReviewRequest.objects.create(
                campaign=campaign,
                recipient=newRecipient
            )
            return redirect('campaigns:campaign_detail', pk=pk)
        else:
            context = {'form': form, 'campaign': campaign}
            return render(request, 'campaigns/review_request_form.html', context)

    form = RecipientForm(campaign=campaign)

    context = {
        'campaign': campaign,
        'form': form,
    }

    return render(request, 'campaigns/review_request_form.html', context)


@login_required
@is_creator_required
@transaction.atomic()
def upload_recipient(request, pk):

    print(url_to_view(request.path))
    campaign = Campaign.objects.get(id=pk)
    context = {'pk': pk}

    # import pdb; pdb.set_trace()

    if request.method == "POST":

        csv_file = request.FILES['file']

        """
        Check for CSV file format
        """
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'This is not a CSV file')
            return redirect('campaigns:recipient_upload', pk=pk)

        colnames = ['first_name', 'last_name',
                    'email', 'extra_field_1', 'extra_field_2']

campaigns/templates/campaigns/evaluation/base_evaluation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- Mobile Viewport -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!--Favicon-->
        <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
        <link rel="manifest" href="/static/favicon/site.webmanifest">
        <link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="/static/favicon/favicon.ico">
        <meta name="msapplication-TileColor" content="#3554d1">
        <meta name="theme-color" content="#3554d1">

        <!--Font Awesome-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">

         <!--Google Fonts-->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
        <title>{{review_request.campaign.intro_template.subject_line}}</title>
    </head>

    <header>
        
        <div class="menu"></div>
        <div class="submenu">
            <div class="flex">
                
                <img class="thumbnail" alt="logo"
                    {% if campaign.creator.logo %} 
                        src="{{campaign.creator.logo.url}}" onerror="this.src='https://detour-app.s3.amazonaws.com/static/img/default_logo.jpg'"
                    {% else %} 
                        src="https://detour-app.s3.amazonaws.com/static/img/default_logo.jpg"
                    {% endif %} 
                >
                
                <div class="website">
                    <h3 class='company-name'>{{campaign.creator.organization}}</h3>
                    <p class="website-url">{{campaign.creator.clean_website_url}}</p>
                </div>
            </div>
        </div>
    </header>

    <body>
        <div class="">
            {% block content %}
            {% endblock %}
        </div>
    </body>

</html>




<script>
    function toggleDisplay() {
        toggle = document.getElementById('altroutes')
        toggle.style.display = toggle.style.display == "block" ? "none" : "block";
    }
</script>

<style>

    *{
        padding: 0;
        margin: 0;
    }

    h1, h2{
        margin-bottom: 5px;
    }

    body {
        text-align:center;
        font-family: 'Open Sans', sans-serif;
        color: {{campaign.intro_template.body_color}};
        background-color: {{campaign.intro_template.background_color}};
    }

    .menu{
        height: 72px;
        background:{{campaign.intro_template.navbar_color}};
    }



    .submenu{
        display: block;
        background-color: white;
        padding: 16px;
        box-shadow: 0px 2px 6px 0px rgb(0 0 0 / 10%);
    }

    .flex{
        display: flex;
        justify-content: center;
        align-items: center;
    }

    #overlay {
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(221, 221, 221, 0.75);
        z-index: 2;
        overflow-y:scroll;
        overflow-x:hidden;
    }

    .modal {
        background-color: #fefefe;
        margin: 19vh auto;
        padding: 45px 15px;
        z-index: 1;
        max-width: 400px;
        border-radius: 10px;
        box-shadow: 0px 2px 6px 0px rgb(0 0 0 / 10%);
    }

    .narrow {
        padding: 25px 40px;
    }

    .cell {
        margin-top: 10px;
        padding: 25px 20px;
        background: #ffffff;  
        border-radius: 10px;
        text-align: left;
        display: flex;
        align-items: center;
        cursor: pointer;
        border: solid 1px rgb(235, 235, 235);
    }

    .toggle{
        font-size: 0.9rem;
        font-weight: 700;
        margin-top: 15px;
        color: #808080;
        fill: #808080;
        cursor: pointer;
        display: flex;
        /* flex-direction: column; */
        justify-content: center;
    }

    .toggle:hover{
        color: #ee7825;
        fill: #ee7825
    }



    label[for="chevronControl"] {
        font-size: 0.9rem;
        font-weight: 700;
        margin-top: 15px;
        color: #808080;
        fill: #808080;
        cursor: pointer;
        display: flex;
        /* flex-direction: column; */
        justify-content: center;
    }

    label[for="chevronControl"]:hover {
        color: #ee7825;
        fill: #ee7825
    }

    #chevronControl {
        display: none;
    }

    #chevronControl:checked + label > svg {
        transform: rotate(180deg);
        -webkit-transform: rotate(180deg);
        -moz-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
    }


    .hidden{
        display:none;
    }

    a:link {
        text-decoration: none;
    }

    a {color:#000000;}         /* Unvisited link  */
    a:visited {color:#000000;} /* Visited link    */
    a:hover {color:#000000;}   /* Mouse over link */
    a:active {color:#000000;}  /* Selected link   */

    .cell:hover {
        background: #f3f6f8; 
    }

    .routing-logo{
        padding-right: 0px;
        width: 35px;
        height: 35px;
        line-height: 35px;
        border-radius: 50px;
    }

    .routing-name{
        padding-left: 10px;
    }

    .list{
        margin: 40px 0px;
    }

    .website{
        text-align: left;
    }

    .thumbnail {
        width: 40px;
        height: 40px;
        margin-right: 10px;
        border-radius: 50%;
    }

    .company-name{
        color:{{campaign.intro_template.heading_color}};
    }

    .website-url{
        /* color:#9A9AAD; */
        color: {{campaign.intro_template.subheading_color}};
    }

    .container {    
        margin: 5px 15px;
    }

    .rating{
        margin: 25px 20px;
    }

    hr.solid{
        border-top: 1px solid rgb(245, 245, 245);
    }

    div.line {
        border-bottom:thin solid rgb(231, 231, 231);
    }

    /* form {
        margin: 10px;
    } */


    label[for="id_comments"] {
        font-size: 1.2rem;
        font-weight: 700;
    }

    textarea, input{
        resize: none;
        border: solid 1px #e0e2e6;  
        border-radius: 10px;
        margin: 10px 0px;
        width: 95%;
        padding: 15px;
        box-sizing: border-box;
        font-size: 1rem;
        font-family: 'Open Sans', sans-serif;
        -webkit-appearance: none;
    }

    textarea:focus, input:focus { 
        outline: none !important;
        background-color: #fcfcfc;
        border-color: {{campaign.intro_template.navbar_color}};
        

    }

    ::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
        color: #a5a5a5;
        line-height: 1.6rem;
        letter-spacing: 0.5px;
        font-family: 'Open Sans', sans-serif;
        font-weight: 400;
    }

    :-ms-input-placeholder { /* Internet Explorer 10-11 */
        color: #707070;
    }

    ::-ms-input-placeholder { /* Microsoft Edge */
        color: #707070;
    }


    .heading {
        margin-bottom: 10px;
        color: {{campaign.intro_template.heading_color}};
    }

    .left{
        text-align: left;
    }

    .center{
        text-align: center;
    }

    .header-box{
        padding: 0px 10px 0px 10px;
    }

    .modal-subject{
        font-size: 1.5rem;
        font-weight: 700;
        margin-bottom: 10px;
    }
  

    .subheading {
        line-height: 1.5;
        margin-bottom: 30px;
        margin-top: 20px;
        color: {{campaign.intro_template.subheading_color}};
        
    }

    .narrow{
        padding: 0px 10%
    }
    
    .white-box {
        background: white;
        padding: 40px;
        max-width: 425px;
        width: 80%;
        min-height: 20em;
        margin: auto;
        margin-top: 20px;
        margin-bottom: 20px;
        box-shadow: 0px 2px 6px 0px rgb(0 0 0 / 10%);
        border-radius: 10px;
    }



    .rate {
        float: center;
        height: 36px;
        padding: 0 10px;
        display: inline-flex;
        flex-direction: row-reverse;
    }
    .rate:not(:checked) > input {
        position:absolute;
        top:-9999px;
    }
    .rate:not(:checked) > label {
        float:right;
        width:1em;
        overflow:hidden;
        white-space:nowrap;
        cursor:pointer;
        font-size:30px;
        color:#ccc;
        /* color: {{campaign.intro_template.subheading_color}}; */
    }
    .rate:not(:checked) > label:before {
        content: '★ ';
    }
    .rate > input:checked ~ label {
        color:gold;
    }
    .rate:not(:checked) > label:hover,
    .rate:not(:checked) > label:hover ~ label {
        color: #deb217;  
    }
    .rate > input:checked + label:hover
    .rate > input:checked + label:hover ~ label,
    .rate > input:checked ~ label:hover,
    .rate > input:checked ~ label:hover ~ label,
    .rate > label:hover ~ input:checked ~ label {
        color: #c59b08;
    }

    .button {
        background-color: {{campaign.intro_template.button_color}};
        border: none;
        font-weight: 600;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor:pointer;
        border-radius: 10px;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        margin-top: 15px;
    }

    .errorlist{
        color: red;
        list-style-type:none;
    }

    .button:hover{
        background: {{campaign.intro_template.hover_button_color}}
    }


    @media only screen and (max-width: 600px) {
        .menu{
            height: 40px;
        }

        .container {
            margin: 10px 0px;
        }
        .white-box {
            padding: 25px 10px;
            width: auto;
        }

        .remove-padding{
            padding: 25px 0px;
        }

        .narrow{
            padding: 0px 10%
        }

        .modal {
            padding: 25px 15px;
            margin: 20vh auto;
        }


        .narrow {
            padding: 25px 7%;
        }


    }

    @media only screen and (max-width: 320px) {
        .narrow {
            padding: 15px 4%;
        }
    }

</style>

campaigns/templates/campaigns/evaluation/comments_form.html
{% extends 'campaigns/evaluation/base_evaluation.html' %}

{% block content %}
<div class="white-box remove-padding">

    <form  method="post" action="">
        {% csrf_token %}
        {{form.as_p}}
        {% csrf_token %}

        <input class="button" type="submit" value="Submit">
    </form>
</div>
{% endblock %} 

campaigns/templates/campaigns/evaluation/email_form.html
{% extends 'campaigns/evaluation/base_evaluation.html' %}

{% block content %}
    <div class="white-box">
        <div class="header-box">
            <h1 class="heading">{{criteria.name}}</h1>
            <!-- <h4 style="color:lightgray; font-size: 0.9rem;">STEP 1 of 2</h2> -->
            <div class="subheading">{{criteria.label}}</div>

            <!-- <a href="/{{slug}}">test</a> -->
            



            <div style="display: flex; justify-content: space-between; margin: 0px 20px">
                <a href="/evaluation/email/{{slug}}/1">
                    <img src="https://nxcso.stripocdn.email/content/guids/CABINET_26b3162452cc59077a9f56695f9c277a/images/12011556881497858.png" alt style="display: block;" width="75">
                </a>
                <a href="/evaluation/email/{{slug}}/2">
                    <img src="https://nxcso.stripocdn.email/content/guids/CABINET_26b3162452cc59077a9f56695f9c277a/images/84901556881536888.png" alt style="display: block;" width="75">
                </a>
                <a href="/evaluation/email/{{slug}}/3">
                    <img src="https://nxcso.stripocdn.email/content/guids/CABINET_26b3162452cc59077a9f56695f9c277a/images/89181556881562856.png" alt style="display: block;" width="75">
                </a>
            </div>

            
<!-- 
            <a href="/evaluation/email/{{slug}}/1">
                <div class="rate">
                        <label for="dsfdf" title="dsfsd"></label> 
                </div>
            </a>

            <a href="/evaluation/email/{{slug}}/2">
                <div class="rate">
                    <label for="dsfdf" title="dsfsd"></label> 
                </div>
            </a>

            <a href="/evaluation/email/{{slug}}/3">
                <div class="rate">
                    <label for="dsfdf" title="dsfsd"></label> 
                </div>
            </a>

            <a href="/evaluation/email/{{slug}}/4">
                <div class="rate">
                    <label for="dsfdf" title="dsfsd"></label> 
                </div>
            </a>

 -->


           

        </div>
    </div>
{% endblock %}

campaigns/templates/campaigns/evaluation/post_redirect.html
{% extends 'campaigns/evaluation/base_evaluation.html' %}

{% block content %}
 
<div id="overlay">
    <div class="modal shadow">
        <div class="narrow">
            <div class="modal-subject">{{campaign.intro_template.redirect_heading}}</div>
            <div class="subheading">{{campaign.intro_template.redirect_subheading}}</div>
            <!-- <a class="cell" href={{route.url}}> -->
            <a class="cell" href="{% url 'campaigns:redirect' epk=evaluation.id rpk=route.id %}">
                <img class="routing-logo" src="{{route.url_thumbnail}}" onerror="this.src='https://detour-app.s3.amazonaws.com/static/img/default_route.png'" alt="{{route.name}}-thumbnail">
                <span class="routing-name">{{route.name}}</span>
            </a>

            <input onClick="toggleDisplay()" type="checkbox" id="chevronControl"/>
            <label class="btn" for="chevronControl">
                <span>More options</span>
                <svg id="chevron" height="24" width="24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.273 9.146l6.354 6.354 6.353-6.354-.707-1.459-5.646 5.647L5.98 7.687z"></path>
                </svg>
            </label>
            
            <div id="altroutes" class="hidden">
                {% if altroutes %} 
                    {% for altroute in altroutes %}
                        <a class="cell" href="{% url 'campaigns:redirect' epk=evaluation.id rpk=altroute.id %}">
                            <img class= "routing-logo" src="{{altroute.url_thumbnail}}" onerror="this.src='https://detour-app.s3.amazonaws.com/static/img/default_route.jpg'" alt="{{altroute.name}}-thumbnail">
                            <span class="routing-name">{{altroute.name}}</span>
                        </a>
                    {% endfor %}            
                {% endif %}
                <a class="cell" href="{{private_review_url}}">
                    <img class= "routing-logo" src="https://detour-app.s3.amazonaws.com/static/img/private37x37.png" alt="private-review">
                    <span class="routing-name">Private review</span>
                </a>
            </div>

        </div>
    </div>  
</div>



{% endblock %}

campaigns/templates/campaigns/evaluation/registration_form.html
{% extends 'campaigns/evaluation/base_evaluation.html' %}

{% block content %} 
<div class="">
    <div class="white-box">
    <div class="header-box">
        <h1 class="heading">{{campaign.intro_template.subject_line}}</h1>
        <div class="subheading">{{campaign.intro_template.body}}</div>
    </div>
  
    <form method="post" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="button" value="Next">
    </form>
</div>
</div>


{% endblock %}